package View;

import Controller.Controlador;
import Model.Planeta;
import Model.PlanetaException;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author MarcMorenoPineda
 */
public class createPlanet extends javax.swing.JDialog {

    /**
     * Creates new form createPlanet
     *
     * @param parent
     */
    public createPlanet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
    }

//GETTER:
    //pondremos getters ya que necesitamos acceder a ellos para el controlador
    //y al ser privados por defecto no podemos
    public javax.swing.JTextField getpName() {
        return pName;
    }

    public javax.swing.JTextField getGalaxy() {
        return Galaxy;
    }

    public javax.swing.JSpinner getPopulationMax() {
        return PopulationMax;
    }

    public javax.swing.JComboBox getClime() {
        return Clime;
    }

    public javax.swing.JRadioButton getFlora() {
        return Flora;
    }

    public javax.swing.JRadioButton getAquatic() {
        return Aquatic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pName = new javax.swing.JTextField();
        text3 = new javax.swing.JLabel();
        text0 = new javax.swing.JLabel();
        cancelCreatePlanet1 = new javax.swing.JButton();
        PopulationMax = new javax.swing.JSpinner();
        text1 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        Galaxy = new javax.swing.JTextField();
        Clime = new javax.swing.JComboBox<>();
        text2 = new javax.swing.JLabel();
        saveCreatePlanet1 = new javax.swing.JButton();
        Flora = new javax.swing.JRadioButton();
        Aquatic = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pName.setFont(new java.awt.Font("Space Bd BT", 0, 15)); // NOI18N
        pName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameActionPerformed(evt);
            }
        });
        getContentPane().add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 125, 42));

        text3.setFont(new java.awt.Font("Space Bd BT", 0, 18)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 255, 255));
        text3.setText("Capacidad máxima del planeta:");
        getContentPane().add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, -1));

        text0.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        text0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/createPlanetTitle.jpg"))); // NOI18N
        getContentPane().add(text0, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 6, -1, -1));

        cancelCreatePlanet1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelCreatePlanet1.setForeground(new java.awt.Color(255, 0, 0));
        cancelCreatePlanet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        cancelCreatePlanet1.setBorder(null);
        cancelCreatePlanet1.setContentAreaFilled(false);
        cancelCreatePlanet1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelCreatePlanet1.setMaximumSize(new java.awt.Dimension(446, 109));
        cancelCreatePlanet1.setMinimumSize(new java.awt.Dimension(446, 109));
        cancelCreatePlanet1.setOpaque(true);
        cancelCreatePlanet1.setPreferredSize(new java.awt.Dimension(446, 107));
        cancelCreatePlanet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCreatePlanet1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancelCreatePlanet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 700, -1, 103));

        PopulationMax.setFont(new java.awt.Font("Space Bd BT", 0, 15)); // NOI18N
        PopulationMax.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(PopulationMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 126, 42));

        text1.setFont(new java.awt.Font("Space Bd BT", 0, 18)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setText("Name Planet:");
        getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        text4.setFont(new java.awt.Font("Space Bd BT", 0, 18)); // NOI18N
        text4.setForeground(new java.awt.Color(255, 255, 255));
        text4.setText("Tipo de clima:");
        getContentPane().add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        Galaxy.setFont(new java.awt.Font("Space Bd BT", 0, 15)); // NOI18N
        Galaxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalaxyActionPerformed(evt);
            }
        });
        getContentPane().add(Galaxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 125, 42));

        Clime.setFont(new java.awt.Font("Space Bd BT", 0, 15)); // NOI18N
        Clime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frío", "Cálido", "Templado" }));
        Clime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClimeActionPerformed(evt);
            }
        });
        getContentPane().add(Clime, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 125, 42));

        text2.setFont(new java.awt.Font("Space Bd BT", 0, 18)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setText("Galaxia a la que pertenece:");
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        saveCreatePlanet1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveCreatePlanet1.setForeground(new java.awt.Color(0, 153, 255));
        saveCreatePlanet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        saveCreatePlanet1.setBorder(null);
        saveCreatePlanet1.setContentAreaFilled(false);
        saveCreatePlanet1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveCreatePlanet1.setMaximumSize(new java.awt.Dimension(446, 109));
        saveCreatePlanet1.setMinimumSize(new java.awt.Dimension(446, 109));
        saveCreatePlanet1.setOpaque(true);
        saveCreatePlanet1.setPreferredSize(new java.awt.Dimension(446, 107));
        saveCreatePlanet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCreatePlanet1ActionPerformed(evt);
            }
        });
        getContentPane().add(saveCreatePlanet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, -1, 103));

        Flora.setFont(new java.awt.Font("Space Bd BT", 0, 18)); // NOI18N
        Flora.setForeground(new java.awt.Color(255, 255, 255));
        Flora.setText("SI tendrá flora roja");
        Flora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloraActionPerformed(evt);
            }
        });
        getContentPane().add(Flora, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        Aquatic.setFont(new java.awt.Font("Space Bd BT", 0, 18)); // NOI18N
        Aquatic.setForeground(new java.awt.Color(255, 255, 255));
        Aquatic.setText("SI tendrá seres acuáticos");
        Aquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AquaticActionPerformed(evt);
            }
        });
        getContentPane().add(Aquatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/final startucom.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 810, -1, 74));

        jLabel1.setBackground(new java.awt.Color(0, 24, 78));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panel de control.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameActionPerformed

    private void cancelCreatePlanet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCreatePlanet1ActionPerformed
        
        //Cerraremos la ventana actual
        dispose();
    }//GEN-LAST:event_cancelCreatePlanet1ActionPerformed

    private void GalaxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalaxyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GalaxyActionPerformed

    private void ClimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClimeActionPerformed

    private void saveCreatePlanet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCreatePlanet1ActionPerformed
        
        //
        try {
            
            if (pName.getText().isEmpty() || Galaxy.getText().isEmpty() || (Integer) (PopulationMax.getValue()) == 0) {
                
                JOptionPane.showMessageDialog(this, "[ ! ] Datos incompletos. Revisa los campos de Name, Galaxy y el número de habitantes", "Recogida datos", JOptionPane.WARNING_MESSAGE);
                
            } else {

                //Acceso del controlador a la vista:
                
                    //es muy importante saber esto, ya que la clase createPlanet es la vista, 
                    //que contiene los componentes de la interfaz (JTextField, JRadioButton, etc)
                    
                    //el Controlador es el encargado de manejar la lógica (en este caso, procesar 
                    //agregar los planetas)
                    
                    //Cuando ponemos "Controlador.createPlanet(p)" dandole acceso al controlador
                    //para que pueda acceder a los componentes de la vista y obtener sus valores
                    
                //Crearemos un nuevo objeto planeta, con los datos de cada uno ya distribuidos
                Planeta p = new Planeta(pName.getText(), Galaxy.getText(), (Integer) PopulationMax.getValue(), (String) Clime.getSelectedItem(), Flora.isSelected(), Aquatic.isSelected());
                
                System.out.println("[createPlanet] entrada de datos correcta");
                
                Controlador.createPlanet(p);
                
                //hacemos que salte el mensaje conforme se ha añadido correctamente
                throw new PlanetaException("[ OK ] El planeta " + p.getName() + " se ha añadido correctamente");
            }
        } catch (PlanetaException e) {
            
            //en caso de que funcione, saltará la excepción: 
            JOptionPane.showMessageDialog(this, e.getMessage(), "Registro planeta", JOptionPane.INFORMATION_MESSAGE);
        }
        
        //Una vez finalizado todo, cerraremos la pestaña
        System.out.println("[createPlanet] planeta creado");
        dispose();
    }//GEN-LAST:event_saveCreatePlanet1ActionPerformed

    private void FloraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloraActionPerformed

    }//GEN-LAST:event_FloraActionPerformed

    private void AquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AquaticActionPerformed

    }//GEN-LAST:event_AquaticActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                createPlanet dialog = new createPlanet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aquatic;
    private javax.swing.JComboBox<String> Clime;
    private javax.swing.JRadioButton Flora;
    private javax.swing.JTextField Galaxy;
    private javax.swing.JSpinner PopulationMax;
    private javax.swing.JButton cancelCreatePlanet1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pName;
    private javax.swing.JButton saveCreatePlanet1;
    private javax.swing.JLabel text0;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    // End of variables declaration//GEN-END:variables
}
