package View;

import Controller.Controlador;
import static Controller.Controlador.getSerByName;
import Model.*;
import java.awt.Color;

/**
 *
 * @author MarcMorenoPineda
 */
public class listBeingPlanet extends javax.swing.JDialog {

    /**
     * Creates new form listBeingPlanet
     */
    public listBeingPlanet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        PlanetaBeingList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        cancelListBeingPlanet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1034, 886));
        setPreferredSize(new java.awt.Dimension(1024, 918));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listBeing.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1030, -1));

        PlanetaBeingList.setBackground(new java.awt.Color(79, 79, 79));
        PlanetaBeingList.setFont(new java.awt.Font("Space Bd BT", 0, 14)); // NOI18N
        PlanetaBeingList.setForeground(new java.awt.Color(255, 255, 255));
        PlanetaBeingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanetaBeingListActionPerformed(evt);
            }
        });
        getContentPane().add(PlanetaBeingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 170, -1));

        jTextPane1.setBackground(new java.awt.Color(79, 79, 79));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Space Bd BT", 0, 14)); // NOI18N
        jTextPane1.setMinimumSize(new java.awt.Dimension(62, 22));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 360, 170));

        cancelListBeingPlanet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelListBeingPlanet.setForeground(new java.awt.Color(255, 0, 0));
        cancelListBeingPlanet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        cancelListBeingPlanet.setBorder(null);
        cancelListBeingPlanet.setContentAreaFilled(false);
        cancelListBeingPlanet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelListBeingPlanet.setOpaque(true);
        cancelListBeingPlanet.setPreferredSize(new java.awt.Dimension(446, 109));
        cancelListBeingPlanet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelListBeingPlanetActionPerformed(evt);
            }
        });
        getContentPane().add(cancelListBeingPlanet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, -1, 101));

        jLabel1.setBackground(new java.awt.Color(0, 24, 78));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panel de control.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/final startucom.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, -1, 74));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//--------------------------------------
// Crearemos un formWindowGainedFocus -> esto hará que siempre que se abra
// createBeing, el comboBox de planeta se rellenará automáticamente
//--------------------------------------
    
    /**
     * -----------------------------------
     * RELLENAR COMBOBOX AUTOMATICAMENTE
     * -----------------------------------
     * 
     * Crearemos un formWindowGainedFocus -> esto hará que siempre que se abra
     * listBeingPlanet, el comboBox de planeta se rellenará automáticamente
     * 
     * @param evt 
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        // Limpiamos el ComboBox antes de agregar los elementos
        PlanetaBeingList.removeAllItems();

        // Obtenemos la lista de planetas desde el controlador
        Controlador.getAllPlanet();

        //Set<Ser>Planetas = Controlador.getPopulation();
        
        // Llenamos el JComboBox con los nombres de los seres
        for (Planeta p : Controlador.getAllPlanet()) {
            
            for(Ser s : p.getPopulation()){
                
                PlanetaBeingList.addItem(s.getName());
            }
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * --------------
     * MOSTRAR SERES
     * --------------
     * 
     * Con ayuda de un combobox recogeremos todos los planetas que hayan en el 
     * hashset de planetas. Para luego mostrarlos y con ".toString" visualizar en
     * un textpane la información de este.
     * 
     * @param evt 
     */
    private void PlanetaBeingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanetaBeingListActionPerformed
        
        // Recogeremos el nombre del ser seleccionado
        String beingName = (String) PlanetaBeingList.getSelectedItem();
        
        //lo pasaremos por el seres
        Ser s = getSerByName(new Ser(beingName));
                            
        //deshabilitamos el panel para que no se pueda editar
        jTextPane1.setEnabled(false);
                  
        //mostraremos el contenido de los seres
        jTextPane1.setText(s.toString());
    }//GEN-LAST:event_PlanetaBeingListActionPerformed

    /**
     * --------------------
     * SALIR DE LA VENTANA
     * --------------------
     * 
     * Usaremos la propiedad dispose() para cerrar la ventana actual
     * 
     * @param evt 
     */
    private void cancelListBeingPlanetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelListBeingPlanetActionPerformed

        //Cerraremos la ventana actual
        dispose();
    }//GEN-LAST:event_cancelListBeingPlanetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listBeingPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listBeingPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listBeingPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listBeingPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                listBeingPlanet dialog = new listBeingPlanet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PlanetaBeingList;
    private javax.swing.JButton cancelListBeingPlanet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
