package View;

import Controller.Controlador;
import static Controller.Controlador.getPlanetByName;
import Model.*;
import java.awt.Color;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author MarcMorenoPineda
 */
public class listPlanet extends javax.swing.JDialog {

    /**
     * Creates new form listPlanet
     */
    public listPlanet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        PlanetaList1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        cancelListPlanet = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listPlanet.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PlanetaList1.setBackground(new java.awt.Color(79, 79, 79));
        PlanetaList1.setFont(new java.awt.Font("Space Bd BT", 0, 14)); // NOI18N
        PlanetaList1.setForeground(new java.awt.Color(255, 255, 255));
        PlanetaList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanetaList1ActionPerformed(evt);
            }
        });
        getContentPane().add(PlanetaList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 160, -1));

        jTextPane2.setBackground(new java.awt.Color(79, 79, 79));
        jTextPane2.setBorder(null);
        jTextPane2.setFont(new java.awt.Font("Space Bd BT", 0, 14)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane2.setDisabledTextColor(new java.awt.Color(79, 79, 79));
        jScrollPane1.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 360, 165));

        cancelListPlanet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelListPlanet.setForeground(new java.awt.Color(255, 0, 0));
        cancelListPlanet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        cancelListPlanet.setBorder(null);
        cancelListPlanet.setContentAreaFilled(false);
        cancelListPlanet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelListPlanet.setOpaque(true);
        cancelListPlanet.setPreferredSize(new java.awt.Dimension(446, 109));
        cancelListPlanet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelListPlanetActionPerformed(evt);
            }
        });
        getContentPane().add(cancelListPlanet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, -1, 101));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/final startucom.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, -1, 74));

        jLabel1.setBackground(new java.awt.Color(0, 24, 78));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panel de control.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jTextPane1.setMinimumSize(new java.awt.Dimension(62, 22));
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 495, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * -----------------
     * MOSTRAR PLANETAS
     * -----------------
     * 
     * Con ayuda de un combobox recogeremos todos los planetas que hayan en el 
     * hashset de planetas. Para luego mostrarlos y con ".toString" visualizar en
     * un textpane la información de este.
     * 
     * @param evt 
     */
    private void PlanetaList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanetaList1ActionPerformed

        // Recogeremos el nombre del planeta seleccionado
        String planetName = (String) PlanetaList1.getSelectedItem();
        
        //y lo pasaremos por el hashset
        Planeta p = getPlanetByName(new Planeta(planetName));
        
        if (!Controlador.okPlanets()) {
                            
            //deshabilitamos el panel para que no se pueda editar
            jTextPane2.setEnabled(false);
            
            //mostraremos el contenido de los planetas
            jTextPane2.setText(p.toString());
            
        } else{
            
            JOptionPane.showMessageDialog(this, "[ X ] El planeta " + p.getName() + " no tiene habitantes", "Planeta vacío", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PlanetaList1ActionPerformed

    /**
     * -----------------------------------
     * RELLENAR COMBOBOX AUTOMATICAMENTE
     * -----------------------------------
     * 
     * Crearemos un formWindowGainedFocus -> esto hará que siempre que se abra
     * listPlanet, el comboBox de planeta se rellenará automáticamente
     * 
     * @param evt 
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        // Limpiamos el ComboBox antes de agregar los elementos
        PlanetaList1.removeAllItems();

        // Obtenemos la lista de planetas desde el controlador
        Controlador.getAllPlanet();

        //con "Set" almacenaremos todos los objetos de Planeta 
        Set<Planeta>planetas = Controlador.getAllPlanet();
        
        // Llenamos el JComboBox con los nombres de los planetas
        for (Planeta p : planetas) {
            
            PlanetaList1.addItem(p.getName());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * --------------------
     * SALIR DE LA VENTANA
     * --------------------
     * 
     * Usaremos la propiedad dispose() para cerrar la ventana actual
     * 
     * @param evt 
     */
    private void cancelListPlanetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelListPlanetActionPerformed

        //Cerraremos la ventana actual
        dispose();
    }//GEN-LAST:event_cancelListPlanetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                listPlanet dialog = new listPlanet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PlanetaList1;
    private javax.swing.JButton cancelListPlanet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
